language: node_js

node_js:
    - 10
    - 11
    - 12
    - 13

matrix:
    fast_finish: true

env:
    - CXX=g++-4.8

addons:
    apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-4.8
