language: node_js

node_js:
    - 5.10.0
    - 5.0.0
    - 4.4.2
    - 4.0.0

matrix:
    fast_finish: true

env:
    - CXX=g++-4.8

addons:
    apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-4.8
